version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - data_volume:/app/data
    environment:
      - FLASK_ENV=development

volumes:
  data_volume: